// Kotlin Gradle Plugin sürümü artık `settings.gradle` plugins bloğunda
// bildiriliyor (Flutter 3.19+ düzeni). Buradaki buildscript classpath'i
// eklenti alt-projelerine ulaşmadığı için kaldırıldı.

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
